SourceFile criteria + UnresolvedReferences criteria
sulir/jamabuild pull request #1
Opened 2023-05-31 20:26 UTC by MilanNosal

Adds SourceFile criteria which allows testing source files presence using glob in pre build phase.

Also adds UnresolvedReferences criterion which attempts to search for "not found" text in output of jdeps tool run on JARs folder of the project in post build phase.

2023-06-01 16:32 UTC, sulir requested changes

2023-06-01 16:32 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/SourceFile.java
> +        PathMatcher matcher = FileSystems.getDefault().getPathMatcher("glob:" + globPattern);
The `path` parameter is an absolute path. Creating a matcher only from the glob pattern is insufficient since it will practically never match (e.g., `*.c` does not match `/home/user/file.c`). See `Project::getPathMatcher`.

2023-06-01 16:32 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/SourceFile.java
> +    public SourceFile(Phase phase, Type type, String globPattern, String contentToSearch) {
This constructor will never be called. There is always only one String parameter - see CriterionFactory::createInstance. The parameter can consist of multiple parts, e.g., separated by a space, but this must be handled in the criterion's code.

2023-06-01 16:32 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/UnresolvedReferences.java
> +            ProcessBuilder pb = new ProcessBuilder(Arrays.asList("jdeps", "-verbose", "-R", jarsDir.toString()));
The path passed to `jdeps` can be a directory - but only a directory of class files, not JAR fies. It is necessary to supply a list of all JAR files in the directory as an argument. Alternatively, a glob pattern (`*.jar`) together with `bash -c "command"` could be used.

Also, the `-verbose` argument is not really necessary, unresolved references are printed anyway.

2023-06-01 21:57 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/SourceFile.java
> +            return paths.anyMatch(path -> matchesGlobAndContent(path));
`path -> matchesGlobAndContent(path)` can be replaced with `this::matchesGlobAndContent`.

2023-06-02 10:54 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/SourceFile.java
> +        PathMatcher matcher = FileSystems.getDefault().getPathMatcher("glob:" + globPattern);
I've updated it to use `.getPathMatcher("glob:**/" + globPattern)` instead, so that it can match any file

2023-06-02 10:55 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/SourceFile.java
> +    public SourceFile(Phase phase, Type type, String globPattern, String contentToSearch) {
Removed this constructor and updated to properly parse parameter coming from CriterionFactory

2023-06-02 11:30 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/SourceFile.java
> +            return paths.anyMatch(path -> matchesGlobAndContent(path));
👍
--

2023-06-02 11:49 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/UnresolvedReferences.java
> +            ProcessBuilder pb = new ProcessBuilder(Arrays.asList("jdeps", "-verbose", "-R", jarsDir.toString()));
I updated it to run jdeps separately for each JAR in jars folder

2023-06-02 12:33 UTC, sulir requested changes
Please resolve two new comments.

2023-06-02 12:33 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/UnresolvedReferences.java
> +        Path jarsDir = project.getJARsDir();
Dependency JARs should be included in the analysis too.

2023-06-02 12:33 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/UnresolvedReferences.java
> +        jdepsCommand.addAll(Arrays.asList("jdeps", "-R"));
Please fix IntelliJ IDEA warnings (of suppress some of them if they are impractical to fix).

2023-06-02 16:37 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/UnresolvedReferences.java
> +        Path jarsDir = project.getJARsDir();
Fixed

2023-06-02 16:37 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/UnresolvedReferences.java
> +        jdepsCommand.addAll(Arrays.asList("jdeps", "-R"));
👍

2023-06-02 21:56 UTC, merged