NativeMethods implementation using ASM
sulir/jamabuild pull request #12
Opened 2023-06-23 17:18 UTC by MilanNosal

Simple implmentation using ASM that traverses classes and looks for methods with nativeopcode

2023-06-24 13:00 UTC, sulir requested changes
The solution using ASM is good, better than the suggested command-line "javap" calls. There are some code style issues though.

2023-06-24 13:00 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/NativeMethods.java
> +                try (Stream<Path> jarsPaths = Files.walk(jarsDir)
The "else" branch is basically a duplicate of the "if" branch with minor differences. It would be better, e.g., to create an empty stream/list, then append project JARs if they exist and then append dependency JARs if they exist. The appending part can be also extracted as a method.

2023-06-24 13:00 UTC, sulir commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.ow2.asm/asm -->
The comment is a bit superfluous.

2023-06-24 13:00 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/NativeMethods.java
> +                     Stream<Path> dependenciesPaths = Files.walk(dependenciesDir)
This line is not aligned (one more space than needed).

2023-06-24 18:50 UTC, sulir commented
Please also add a short description to the list of supported criteria in README.

2023-06-26 10:55 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/NativeMethods.java
> +                     Stream<Path> dependenciesPaths = Files.walk(dependenciesDir)
it's aligned to body in `try`... anyway, the comment is obsolete now, as I refactored

2023-06-26 10:55 UTC, MilanNosal commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.ow2.asm/asm -->
Removed

2023-06-26 10:56 UTC, MilanNosal commented on src/main/java/com/github/sulir/jamabuild/criteria/NativeMethods.java
> +                try (Stream<Path> jarsPaths = Files.walk(jarsDir)
Fixed this issue by refactoring, and also applied the solution to the UnresolvedReferences implementation, which suffered from the same issue

2023-06-26 14:48 UTC, sulir commented on src/main/java/com/github/sulir/jamabuild/criteria/NativeMethods.java
> +                try (Stream<Path> jarsPaths = Files.walk(jarsDir)
I extracted also smaller duplicates from NativeMethods and UnresolvedReferences in cbb2088 and 18f1bbe.

2023-06-26 14:49 UTC, merged